/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListingPropertyIdRouteImport } from './routes/listing.$propertyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingPropertyIdRoute = ListingPropertyIdRouteImport.update({
  id: '/listing/$propertyId',
  path: '/listing/$propertyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/listing/$propertyId': typeof ListingPropertyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/listing/$propertyId': typeof ListingPropertyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/listing/$propertyId': typeof ListingPropertyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/listing/$propertyId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/listing/$propertyId'
  id: '__root__' | '/' | '/listing/$propertyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ListingPropertyIdRoute: typeof ListingPropertyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$propertyId': {
      id: '/listing/$propertyId'
      path: '/listing/$propertyId'
      fullPath: '/listing/$propertyId'
      preLoaderRoute: typeof ListingPropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ListingPropertyIdRoute: ListingPropertyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
