name: Deploy Static Site to Dist Branch

on:
  push:
    branches:
      - main  # ή master, ανάλογα πώς λέγεται το branch σου

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to gh-pages branch (dist output)
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: release-dist # Αυτό θα φτιάξει ένα νέο branch που θα έχει ΜΟΝΟ τα έτοιμα αρχεία
